version: '3'
services:
  node:
    container_name: node
    build: .
    volumes:
      - "./app:/src/app"
    environment:
      - token=${SLACK_BOT_TOKEN}
      - slack_user=${SLACK_USER}
      - firebase_config_apiKey=${FIREBASE_CONFIG_apiKey}
      - firebase_config_authDomain=${FIREBASE_CONFIG_authDomain}
      - firebase_config_databaseURL=${FIREBASE_CONFIG_databaseURL}
      - firebase_config_storageBucket=${FIREBASE_CONFIG_storageBucket}
      - firebase_config_messagingSenderId=${FIREBASE_CONFIG_messagingSenderId}
      - google_api_client_id=${GOOGLE_API_CLIENT_ID}
      - google_api_client_secret=${GOOGLE_API_CLIENT_SECRET}
      - google_api_redirect_url=${GOOGLE_API_REDIRECT_URL}
